-- MySQL Script generated by MySQL Workbench
-- Wed Feb  3 22:20:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema baechoo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baechoo` DEFAULT CHARACTER SET utf8 ;
USE `baechoo` ;


-- -----------------------------------------------------
-- Schema `baechoo`.`init`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS `Product`;
DROP TABLE IF EXISTS `Like`;
DROP TABLE IF EXISTS `Order`;
-- -----------------------------------------------------
-- Table `baechoo`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baechoo`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(40) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baechoo`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baechoo`.`Product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `price` INT NOT NULL DEFAULT 0,
  `description` VARCHAR(400) NULL,
  `picture_url` VARCHAR(45) NOT NULL,
  `upload_date` TIMESTAMP NOT NULL,
  `update_date` TIMESTAMP NOT NULL,
  `views` INT NOT NULL DEFAULT 0,
  `on_sale`	BOOLEAN	NOT NULL,
  `like_count`	INT	NULL,
  PRIMARY KEY (`product_id`, `user_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `product_fk1`
    FOREIGN KEY (`user_id`)
    REFERENCES `baechoo`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baechoo`.`Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baechoo`.`Like` (
  `like_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`like_id`, `user_id`, `product_id`),
  UNIQUE INDEX `like_id_UNIQUE` (`like_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `like_fk2_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `like_fk1`
    FOREIGN KEY (`user_id`)
    REFERENCES `baechoo`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `like_fk2`
    FOREIGN KEY (`product_id`)
    REFERENCES `baechoo`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baechoo`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baechoo`.`Order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `user_id`, `product_id`),
  INDEX `order_fk1_idx` (`user_id` ASC) VISIBLE,
  INDEX `order_fk2_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_fk1`
    FOREIGN KEY (`user_id`)
    REFERENCES `baechoo`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_fk2`
    FOREIGN KEY (`product_id`)
    REFERENCES `baechoo`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;