use baechoo;
truncate table User;

insert into User (user_id, nickname, email, password, enabled) values (1, 'Sherry', 'scanadine0@mapy.cz', 'DVUG6YUGSnSi', 1);
insert into User (user_id, nickname, email, password, enabled) values (2, 'Rainer', 'rtownsley1@twitter.com', 'fqOWrIXOLs', 1);
insert into User (user_id, nickname, email, password, enabled) values (3, 'Alayne', 'avalance2@google.com.hk', 'wG8rWCPUAjJz', 1);
insert into User (user_id, nickname, email, password, enabled) values (4, 'Charlotta', 'cscholte3@vkontakte.ru', '68d0Iyf5R4yN', 1);
insert into User (user_id, nickname, email, password, enabled) values (5, 'Jordan', 'jbawles4@paginegialle.it', 'VX5mWxHX', 1);
insert into User (user_id, nickname, email, password, enabled) values (6, 'Nadean', 'ncompford5@tuttocitta.it', 'C64sXZ', 1);
insert into User (user_id, nickname, email, password, enabled) values (7, 'Sharleen', 'strittam6@icio.us', 'TRMgIqdUHS2u', 1);
insert into User (user_id, nickname, email, password, enabled) values (8, 'Sherri', 'sclohisey7@ehow.com', 'ZQsQ9CawB4df', 1);
insert into User (user_id, nickname, email, password, enabled) values (9, 'Ruthy', 'rflanner8@apple.com', 'cqI4ub', 1);
insert into User (user_id, nickname, email, password, enabled) values (10, 'Waylin', 'wwickman9@yahoo.co.jp', 'KajfFTaWjr', 1);
insert into User (user_id, nickname, email, password, enabled) values (11, 'Sarita', 'srydzynskia@baidu.com', 'awxBpU8P', 1);
insert into User (user_id, nickname, email, password, enabled) values (12, 'Timotheus', 'twalheddb@samsung.com', 'HtJt4qwN', 1);
insert into User (user_id, nickname, email, password, enabled) values (13, 'Shalna', 'scisecc@businesswire.com', 'hts3qeaJUXkY', 1);
insert into User (user_id, nickname, email, password, enabled) values (14, 'Sid', 'slissandrid@yale.edu', 'HzMDZtj', 1);
insert into User (user_id, nickname, email, password, enabled) values (15, 'Holly', 'hbobasche@ask.com', 'ygD6ASO69D', 1);
insert into User (user_id, nickname, email, password, enabled) values (16, 'Irena', 'ifalshawf@marketwatch.com', 'iqojsl', 1);
insert into User (user_id, nickname, email, password, enabled) values (17, 'Gillie', 'gvlahosg@usda.gov', '7JkIUh', 1);
insert into User (user_id, nickname, email, password, enabled) values (18, 'Ilario', 'ihurrenh@alibaba.com', 'bV0yNKNOdh9D', 1);
insert into User (user_id, nickname, email, password, enabled) values (19, 'Electra', 'egotcliffi@nydailynews.com', 'MUQTZI6', 1);
insert into User (user_id, nickname, email, password, enabled) values (20, 'Carola', 'cfulkerj@delicious.com', 'NaG6Q6FX3z2u', 1);
insert into User (user_id, nickname, email, password, enabled) values (21, 'Marris', 'mmocklerk@yellowbook.com', 'VBNN9OHN8u', 1);
insert into User (user_id, nickname, email, password, enabled) values (22, 'Page', 'piacobinil@sina.com.cn', 'mRbbhtNPkW', 1);
insert into User (user_id, nickname, email, password, enabled) values (23, 'Syd', 'sdivinym@uiuc.edu', 'rKMcNmHtNwB', 1);
insert into User (user_id, nickname, email, password, enabled) values (24, 'Ali', 'agladechen@time.com', 'YYURHhvBpm', 1);
insert into User (user_id, nickname, email, password, enabled) values (25, 'Marcellus', 'mnetleyo@economist.com', 'Hw1FKh5', 1);
insert into User (user_id, nickname, email, password, enabled) values (26, 'Emmerich', 'emarjanskip@ovh.net', 'z2QhwDXF', 1);
insert into User (user_id, nickname, email, password, enabled) values (27, 'Carmela', 'cegglestonq@surveymonkey.com', 'GKYtq08ZUE', 1);
insert into User (user_id, nickname, email, password, enabled) values (28, 'Ingeberg', 'iahmadr@liveinternet.ru', 'poR9fJ', 1);
insert into User (user_id, nickname, email, password, enabled) values (29, 'Lew', 'lgarvins@census.gov', 'UOgf3kh', 1);
insert into User (user_id, nickname, email, password, enabled) values (30, 'Vick', 'vtolchardt@list-manage.com', '4Y565gyeXD7', 1);
